// 从 antd 中导出自己使用的 icon 减少打包体积

export { default as SmileOutline } from '@ant-design/icons/lib/outline/SmileOutline'
export { default as PlusOutline } from '@ant-design/icons/lib/outline/PlusOutline'
export { default as LoadingOutline } from '@ant-design/icons/lib/outline/LoadingOutline'
export { default as BookOutline } from '@ant-design/icons/lib/outline/BookOutline'
export { default as EditOutline } from '@ant-design/icons/lib/outline/EditOutline'
export { default as MessageOutline } from '@ant-design/icons/lib/outline/MessageOutline'
export { default as GlobalOutline } from '@ant-design/icons/lib/outline/GlobalOutline'
export { default as ContactsOutline } from '@ant-design/icons/lib/outline/ContactsOutline'
export { default as BuildOutline } from '@ant-design/icons/lib/outline/BuildOutline'
export { default as UserOutline } from '@ant-design/icons/lib/outline/UserOutline'
export { default as TagsOutline } from '@ant-design/icons/lib/outline/TagsOutline'
export { default as ClockCircleOutline } from '@ant-design/icons/lib/outline/ClockCircleOutline'
export { default as EyeOutline } from '@ant-design/icons/lib/outline/EyeOutline'
export { default as DeleteOutline } from '@ant-design/icons/lib/outline/DeleteOutline'
export { default as BarcodeOutline } from '@ant-design/icons/lib/outline/BarcodeOutline'
export { default as LockOutline } from '@ant-design/icons/lib/outline/LockOutline'
export { default as CheckCircleOutline } from '@ant-design/icons/lib/outline/CheckCircleOutline'
export { default as InfoCircleOutline } from '@ant-design/icons/lib/outline/InfoCircleOutline'
export { default as ExclamationCircleOutline } from '@ant-design/icons/lib/outline/ExclamationCircleOutline'
export { default as CloseCircleOutline } from '@ant-design/icons/lib/outline/CloseCircleOutline'
export { default as CloseOutline } from '@ant-design/icons/lib/outline/CloseOutline'
export { default as LeftOutline } from '@ant-design/icons/lib/outline/LeftOutline'
export { default as RightOutline } from '@ant-design/icons/lib/outline/RightOutline'
export { default as DashboardOutline } from '@ant-design/icons/lib/outline/DashboardOutline'
export { default as BellOutline } from '@ant-design/icons/lib/outline/BellOutline'